[package]
name = "qfall-math"
version = "0.1.0"
edition = "2021"
autobenches = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
flint-sys = "0.7.2"
fraction = "0.13.1"
libc = "0.2.139"
paste = "1.0.11"
regex = "1"
serde = {version="1.0.150", features=["derive"]}
serde_json = "1.0.89"
string-builder = "0.2.0"
thiserror = "1.0"

[profile.bench]
debug = true

[[package.metadata.bench]]
name = "benchmarks"
harness = false
autodiscovery = false
